//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public string idCart { get; set; }
        public string orderItem { get; set; }
        public Nullable<int> totalPrice { get; set; }
        public string status { get; set; }
        public string bank { get; set; }
        public string phone { get; set; }
        public string nameAgent { get; set; }
    }
}
