//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class managePhoneProductEntities : DbContext
    {
        public managePhoneProductEntities(System.Data.SqlClient.SqlConnection connection)
            : base("name=managePhoneProductEntities")
        {
        }

        public managePhoneProductEntities()
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<detailOrder> detailOrders { get; set; }
        public virtual DbSet<detailReceipt> detailReceipts { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<receipt> receipts { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
    }
}
